FROM node:20-alpine AS build

WORKDIR /app
COPY frontend/package*.json ./
RUN npm ci
COPY frontend ./

ARG VITE_PMTILES_URL
ARG VITE_MAP_STYLE_URL
ARG VITE_MAP_GLYPHS_URL
ENV VITE_PMTILES_URL=$VITE_PMTILES_URL
ENV VITE_MAP_STYLE_URL=$VITE_MAP_STYLE_URL
ENV VITE_MAP_GLYPHS_URL=$VITE_MAP_GLYPHS_URL
RUN npm run build

FROM nginx:1.27-alpine
COPY deployment/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80