"""add_graph_actions_table

Revision ID: 5a2ae4ac2896
Revises:
Create Date: 2026-03-17 12:58:25.149572+00:00

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5a2ae4ac2896"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_id"), "projects", ["id"], unique=False)
    op.create_table(
        "artifacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "artifact_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_artifacts_id"), "artifacts", ["id"], unique=False)
    op.create_table(
        "graphs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("locked_by", sa.Integer(), nullable=True),
        sa.Column("locked_at", sa.DateTime(), nullable=True),
        sa.Column("lock_expires", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_graphs_project", "graphs", ["project_id"], unique=False)
    op.create_table(
        "project_schemas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column(
            "schema_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_project_schemas_id"), "project_schemas", ["id"], unique=False
    )
    op.create_table(
        "artifact_relations",
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("relation_type", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["source_id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("source_id", "target_id", "relation_type"),
    )
    op.create_table(
        "artifact_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("artifact_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "changed_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("changed_by", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(["artifact_id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("artifact_id", "version", name="uq_artifact_version"),
    )
    op.create_index(
        op.f("ix_artifact_versions_id"), "artifact_versions", ["id"], unique=False
    )
    op.create_table(
        "edge_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("schema_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "source_types", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "target_types", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("color", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["schema_id"], ["project_schemas.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_edge_types_id"), "edge_types", ["id"], unique=False)
    op.create_table(
        "edges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("graph_id", sa.Integer(), nullable=False),
        sa.Column("edge_id", sa.String(length=100), nullable=False),
        sa.Column("source_node", sa.String(length=100), nullable=False),
        sa.Column("target_node", sa.String(length=100), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["graph_id"], ["graphs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_edges_graph_edge", "edges", ["graph_id", "edge_id"], unique=True
    )
    op.create_index("ix_edges_graph_id", "edges", ["graph_id"], unique=False)
    op.create_index(
        "ix_edges_source", "edges", ["graph_id", "source_node"], unique=False
    )
    op.create_index(
        "ix_edges_target", "edges", ["graph_id", "target_node"], unique=False
    )
    op.create_index("ix_edges_type", "edges", ["type"], unique=False)
    op.create_table(
        "graph_actions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("artifact_id", sa.Integer(), nullable=False),
        sa.Column("action_type", sa.String(length=50), nullable=False),
        sa.Column("before_state", sa.JSON(), nullable=False),
        sa.Column("after_state", sa.JSON(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("user_type", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("plugin_id", sa.String(length=100), nullable=True),
        sa.Column("group_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["artifact_id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_graph_actions_artifact_id", "graph_actions", ["artifact_id"], unique=False
    )
    op.create_index(
        "ix_graph_actions_artifact_timestamp",
        "graph_actions",
        ["artifact_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        "ix_graph_actions_group", "graph_actions", ["group_id"], unique=False
    )
    op.create_table(
        "node_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("schema_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("color", sa.String(length=50), nullable=True),
        sa.Column("icon", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["schema_id"], ["project_schemas.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_node_types_id"), "node_types", ["id"], unique=False)
    op.create_table(
        "nodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("graph_id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.String(length=100), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("position_x", sa.Float(), nullable=True),
        sa.Column("position_y", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["graph_id"], ["graphs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_nodes_graph_id", "nodes", ["graph_id"], unique=False)
    op.create_index(
        "ix_nodes_graph_node", "nodes", ["graph_id", "node_id"], unique=True
    )
    op.create_index(
        "ix_nodes_position",
        "nodes",
        ["graph_id", "position_x", "position_y"],
        unique=False,
    )
    op.create_index("ix_nodes_type", "nodes", ["type"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_nodes_type", table_name="nodes")
    op.drop_index("ix_nodes_position", table_name="nodes")
    op.drop_index("ix_nodes_graph_node", table_name="nodes")
    op.drop_index("ix_nodes_graph_id", table_name="nodes")
    op.drop_table("nodes")
    op.drop_index(op.f("ix_node_types_id"), table_name="node_types")
    op.drop_table("node_types")
    op.drop_index("ix_graph_actions_group", table_name="graph_actions")
    op.drop_index("ix_graph_actions_artifact_timestamp", table_name="graph_actions")
    op.drop_index("ix_graph_actions_artifact_id", table_name="graph_actions")
    op.drop_table("graph_actions")
    op.drop_index("ix_edges_type", table_name="edges")
    op.drop_index("ix_edges_target", table_name="edges")
    op.drop_index("ix_edges_source", table_name="edges")
    op.drop_index("ix_edges_graph_id", table_name="edges")
    op.drop_index("ix_edges_graph_edge", table_name="edges")
    op.drop_table("edges")
    op.drop_index(op.f("ix_edge_types_id"), table_name="edge_types")
    op.drop_table("edge_types")
    op.drop_index(op.f("ix_artifact_versions_id"), table_name="artifact_versions")
    op.drop_table("artifact_versions")
    op.drop_table("artifact_relations")
    op.drop_index(op.f("ix_project_schemas_id"), table_name="project_schemas")
    op.drop_table("project_schemas")
    op.drop_index("ix_graphs_project", table_name="graphs")
    op.drop_table("graphs")
    op.drop_index(op.f("ix_artifacts_id"), table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index(op.f("ix_projects_id"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
